language: android

android:
  components:
    - tools
    - platform-tools
    - android-21
    - sys-img-armeabi-v7a-android-21

jdk:
  - oraclejdk8

before_script:
  # Install SDK license so Android Gradle plugin can install dependencies.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Start the emulator to run connected tests.
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew build checkstyle test
  - adb shell input keyevent 82
  - ./gradlew connectedCheck

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
