language: android

android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-25
    - android-25
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew build checkstyle test

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
